[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --prefix frontend",
  "npm ci --prefix backend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "cd backend && npx prisma generate && cd .."
]

[start]
cmd = "node backend/server.js"
