[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix frontend --legacy-peer-deps --include=dev",
  "npm install --prefix backend --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "cd backend && npx prisma generate && cd .."
]

[start]
cmd = "node backend/server.js"
